Measure overall, testsuite and test duration and write into junit
tcunit/TcUnit pull request #159
Opened 2021-08-22 08:47 UTC by stefanbesler

2021-09-02 12:13 UTC, sagatowski commented
Hi! Sorry for late reply. Thanks for looking into this. I really like this function. Is it possible that you could use the latest TwinCAT 3.1.4022.x to do the changes though? (according to https://github.com/tcunit/TcUnit/blob/master/CONTRIBUTING.md).

What is the duration measured in? MS?
I guess that if we want to have this included in the JUnit XML-file we will also need to update the [TcUnit-Runner](https://github.com/tcunit/TcUnit-Runner).

Did you try to run the [TcUnit-Verifier](https://github.com/tcunit/TcUnit/tree/master/TcUnit-Verifier) with the new version of TcUnit, just to check that no functionality has been broken?

2022-01-11 16:49 UTC, stefanbesler commented
so, half a year later ... :-)

> Is it possible that you could use the latest TwinCAT 3.1.4022.x to do the changes though?
done, tested it on 4022.29

> What is the duration measured in? MS?
it was in microseconds before, but I changed to seconds, which is according to junit's specification or at least how the Jenkins plugins interprets it

> I guess that if we want to have this included in the JUnit XML-file we will also need to update the TcUnit-Runner.
Well, I would have prefered to only consider the duration in the xml output of TcUnit, but anyway ... I am on it, I will make a pull request in TcUnit-Runner as well

> Did you try to run the TcUnit-Verifier with the new version of TcUnit, just to check that no functionality has been broken?
I ran TcUnit-Verifier, but I had to modify some stuff to get it working (change IDE and Twincat Version that is verified with), would you run it on your setup as well please?

2022-01-26 07:04 UTC, sagatowski commented
Sorry for late response, been really busy lately...
I will review this, but one thing I noticed is that there are no tests added for this functionality into the [TcUnit-Verifier](https://github.com/tcunit/TcUnit/tree/master/TcUnit-Verifier). Is it possible to add a few tests to make sure that you get the expected output?

2022-01-26 10:11 UTC, stefanbesler commented
I added and changed some tests for the durations functionality

2022-01-26 11:51 UTC, iadonkey commented on TcUnit-Verifier/TcUnit-Verifier_DotNet/TcUnit-Verifier/FB_ExtendedTestInformation.cs
> +            AssertMessageCount(duration, 260, EnvDTE80.vsBuildErrorLevel.vsBuildErrorLevelLow);
For the %f see AreErrorItemsContainingTestMessage, there %f is replaced with a regular expression for floating point values

2022-01-26 11:52 UTC, stefanbesler commented on TcUnit-Verifier/TcUnit-Verifier_DotNet/TcUnit-Verifier/FB_ExtendedTestInformation.cs
> +        }
For %f see AreErrorItemsContainingTestMessage below, there %s is replaces with a regular expression to match floating point values

2022-01-26 11:54 UTC, stefanbesler commented on TcUnit-Verifier/TcUnit-Verifier_DotNet/TcUnit-Verifier/TestFunctionBlockAssert.cs
>          }
The regular expression match is notably slower than the mere Contains statement, AreErrorItemsContainingTestMessage is called a lot ... For this reason I added seperate branches, if no floating-point-number wildard is contained in testMessage (%f) I fallback to the "old" method. Otherwise %f gets replaces with a regex for floating point values.

2022-02-07 12:53 UTC, Navid-Mashayekh commented on TcUnit/TcUnit/POUs/FB_TestSuite.TcPOU
> +AddTest REF= Tests[IteratorCounter];]]></ST>
Hi @stefanbesler 
using IteratorCounter here as an index doesn't work some time, in some cases that there are multiple tests with same name or test should be ignored you will get a wrong number!
I had same issue in #179 and finally I added a new method in FB_TestSuite to get the current test instance.

2022-02-07 12:57 UTC, Navid-Mashayekh requested changes

2022-02-07 12:57 UTC, Navid-Mashayekh commented on TcUnit/TcUnit/POUs/FB_TestSuite.TcPOU
> +AddTest REF= Tests[IteratorCounter];]]></ST>
Hi @stefanbesler 
using IteratorCounter here as an index doesn't work some time, in some cases that there are multiple tests with same name or test should be ignored you will get a wrong number!
I had same issue in #179 and finally I added a new method in FB_TestSuite to get the current test instance.

2022-04-18 16:45 UTC, sagatowski requested changes
First of all, sorry for the long delay of reviewing this PR (as you may know, I'm spending all my spare-time on the TwinCAT YouTube course). Thanks for this awesome PR. I've added some review comments. Could you also look into the comment of @Navid-Mashayekh?

2022-04-18 16:45 UTC, sagatowski commented on TcUnit/TcUnit/GVLs/GVL_TcUnit.TcGVL
> +    GetCpuAccount : Tc2_System.GETCPUACCOUNT;
This is not available under Windows CE, and I know several users are running their unit tests on controllers like the CX8190 (WinCE). Is it possible to replace with something else?

2022-04-18 16:45 UTC, sagatowski commented on TcUnit/TcUnit/DUTs/ST_TestSuiteResult.TcDUT
> +    Duration : LREAL;
In seconds as well?

2022-04-18 16:45 UTC, sagatowski commented on TcUnit/TcUnit/POUs/FB_Test.TcPOU
> +Duration := UDINT_TO_LREAL(FinishedAt - StartedAt) / 10000000; // seconds]]></ST>
Possible to replace the magic number 10000000 with a VAR_CONSTANT that explains what this is?

2022-04-18 16:45 UTC, sagatowski commented on TcUnit/TcUnit/POUs/FB_Test.TcPOU
> +THEN
move THEN up, so it matches the rest of the style.

2022-04-18 16:45 UTC, sagatowski commented on TcUnit/TcUnit/POUs/FB_TestSuite.TcPOU
> +    GetCpuAccount : Tc2_System.GETCPUACCOUNT;
Not available for Windows CE, which would break TcUnit for some users.
Also, any reason why we need to use a separate instance of GETCPUACCOUNT? Should we get rid of the global one instead?

2022-04-18 16:45 UTC, sagatowski commented on TcUnit/TcUnit/POUs/FB_TestSuite.TcPOU
> +    StartedAt : UDINT;
Timestamp in what format?...

2022-04-18 16:45 UTC, sagatowski commented on TcUnit/TcUnit/POUs/FB_TestSuite.TcPOU
> +Duration := Duration + UDINT_TO_LREAL(timestamp - StartedAt) / 10000000; // seconds]]></ST>
Replace 10000000 with vaR_constant.

2022-04-18 16:45 UTC, sagatowski commented on TcUnit/TcUnit/POUs/Functions/TEST_FINISHED_NAMED.TcPOU
> +    FinishedAt : UDINT;
What is the unit of FinishedAt? Is it some form of timestamp? What format is it?

2022-04-18 16:45 UTC, sagatowski commented on TcUnit/TcUnit/TcUnit.plcproj
> +    <ProjectVersion>1.2.2.0</ProjectVersion>
No need to increment this. I will increment it before release.

2022-04-18 16:45 UTC, sagatowski commented on TcUnit/TcUnit/GVLs/GVL_TcUnit.TcGVL
> +    (* Timestamp for the first entry into on of the Run methods *)
I don't understand what this means.... "entry into on of the run methods"?

2022-04-18 17:38 UTC, sagatowski commented on TcUnit-Verifier/TcUnit-Verifier_DotNet/TcUnit-Verifier/FB_ExtendedTestInformation.cs
> +            AssertMessageCount(duration, 260, EnvDTE80.vsBuildErrorLevel.vsBuildErrorLevelLow);
What is this 260? Is it the total number of tests? Does it need to be incremented every time a new test is added?

2022-04-18 17:40 UTC, sagatowski commented on TcUnit/TcUnit/DUTs/ST_TestCaseResult.TcDUT
> +    Duration : LREAL;
Is this in seconds?

2022-04-18 17:41 UTC, sagatowski commented on TcUnit/TcUnit/POUs/FB_TcUnitRunner.TcPOU
> +THEN
Move the THEN up to the IF to align with the rest of the code formatting.

2022-04-18 17:42 UTC, sagatowski commented on TcUnit/TcUnit/POUs/FB_TcUnitRunner.TcPOU
> +THEN
Same as before (move THEN to same line as IF).

2022-04-18 17:43 UTC, sagatowski commented on TcUnit/TcUnit/POUs/FB_Test.TcPOU
> +    Duration : LREAL; // Duration of the test in microseconds
Why is it microseconds here, but seconds above?

2022-04-18 17:45 UTC, sagatowski commented on TcUnit/TcUnit/POUs/FB_Test.TcPOU
> +      <Declaration><![CDATA[METHOD SetStartedAtIfNotSet
Possible to set access modifier on the method?

2022-04-18 17:46 UTC, sagatowski commented on TcUnit/TcUnit/POUs/FB_Test.TcPOU
> +    Timestamp : UDINT;
What is the format of this timestamp?

2022-04-18 17:47 UTC, sagatowski commented on TcUnit/TcUnit/GVLs/GVL_TcUnit.TcGVL
> +    StartedAt : UDINT;
What is the format of this? Some timestamp format...?

2022-04-18 17:48 UTC, sagatowski commented on TcUnit/TcUnit/GVLs/GVL_TcUnit.TcGVL
> +    (* Timestamp for the first entry into on of the Run methods *)
What is the difference between `StartedAt` and `CurrentTestNameStartedAt`?

2022-04-18 17:55 UTC, stefanbesler commented on TcUnit/TcUnit/POUs/FB_TestSuite.TcPOU
> +AddTest REF= Tests[IteratorCounter];]]></ST>
thanks @Navid-Mashayekh , I used your solution for this

2022-04-18 18:36 UTC, stefanbesler commented on TcUnit/TcUnit/POUs/FB_Test.TcPOU
> +    Duration : LREAL; // Duration of the test in microseconds
It actually is seconds here, I forgot to change the comment

2022-04-18 18:38 UTC, stefanbesler commented on TcUnit/TcUnit/GVLs/GVL_TcUnit.TcGVL
> +    (* Timestamp for the first entry into on of the Run methods *)
into *one* of the run methods (RUN, RUN_IN_SEQUENCE)

2022-04-18 18:40 UTC, stefanbesler commented on TcUnit/TcUnit/POUs/FB_TestSuite.TcPOU
> +    GetCpuAccount : Tc2_System.GETCPUACCOUNT;
Only the global one is needed, forgot to delete this instance

2022-04-18 18:42 UTC, stefanbesler commented on TcUnit/TcUnit/POUs/FB_Test.TcPOU
> +Duration := UDINT_TO_LREAL(FinishedAt - StartedAt) / 10000000; // seconds]]></ST>
Don't know, for this simple conversion from 100ns to s, I personally feel it is easier to understand to simply see the number, but I can change it

2022-04-18 18:44 UTC, stefanbesler commented on TcUnit/TcUnit/POUs/FB_TestSuite.TcPOU
> +Duration := Duration + UDINT_TO_LREAL(timestamp - StartedAt) / 10000000; // seconds]]></ST>
We can use GETCPUCOUNTER instead, but this FB uses a 64bit variable (well 2x 32bit variables that have to be combined to 64 bit) and I think this breaks CX8190 compability as well?
I will refactor the call to the timer into a function and return 0 on 32bit systems ...

2022-04-18 18:54 UTC, stefanbesler commented on TcUnit-Verifier/TcUnit-Verifier_DotNet/TcUnit-Verifier/FB_ExtendedTestInformation.cs
> +            AssertMessageCount(duration, 260, EnvDTE80.vsBuildErrorLevel.vsBuildErrorLevelLow);
Good questions, I think it is just the number of messages until the first time Test duration should appear. I just adapated the tests that were already there ...

2023-04-29 20:17 UTC, merged

2023-04-29 20:17 UTC, sagatowski commented
Better late than never. I did some minor corrections to your PR. Thank you so much for your contribution @stefanbesler.

2023-04-30 19:11 UTC, sagatowski commented
@stefanbesler  Note that this new feature doesn't work with sequenced tests. Check this issue: https://github.com/tcunit/TcUnit/issues/210.
Would you have time to look into it?

2023-05-01 12:41 UTC, sagatowski commented
@stefanbesler I've also found a second issue with this PR. See #211.

2024-07-28 12:59 UTC, sagatowski commented
@stefanbesler 
This PR is still haunting us...
See:
- https://github.com/tcunit/TcUnit/pull/231 and
- https://github.com/tcunit/TcUnit/issues/228